export const clinics = {
  id: 'clinics',
  aliases: ['physiotherapy', 'physio', 'clinic', 'clinics', 'fisioterapia', 'clinica', 'clinicas'],
  terms: {
    en: {
      treatments: [
        'dry needling',
        'shockwave',
        'sports massage',
        'acupuncture',
        'McKenzie Method',
        'gait analysis',
        'ACL rehabilitation',
        'hydrotherapy',
        'joint mobilisation',
      ],
      bodies: [
        'HCPC',
        'MCSP',
        'CSP',
        'Chartered Society of Physiotherapy',
        'Health & Care Professions Council',
        'BUPA',
        'AXA Health',
        'CQC',
      ],
      conditions: [
        'sciatica',
        'tendinopathy',
        'whiplash',
        'lumbar spine',
        'plantar fasciitis',
        'frozen shoulder',
        'rotator cuff',
        'lower back pain',
        'sports injuries',
        'post-surgery rehab',
      ],
    },
    es: {
      treatments: [
        'punción seca',
        'ondas de choque',
        'masaje deportivo',
        'ejercicio terapéutico',
        'readaptación deportiva',
        'drenaje linfático',
        'vendaje neuromuscular',
        'osteopatía',
      ],
      bodies: [
        'Colegio de Fisioterapeutas',
        'colegiado',
        'colegiada',
        'CFC',
        'Seguridad Social',
        'Adeslas',
        'Sanitas',
      ],
      conditions: [
        'ciática',
        'lumbalgia',
        'cervicalgia',
        'tendinopatía',
        'hernia discal',
        'esguince',
        'fascitis plantar',
        'hombro congelado',
        'latigazo cervical',
      ],
    },
  },
};
