export const ecommerce = {
  id: 'ecommerce',
  aliases: [
    'ecommerce',
    'e-commerce',
    'online shop',
    'online store',
    'webshop',
    'tienda online',
    'comercio electronico',
  ],
  terms: {
    en: {
      productTerms: [
        'whole bean',
        'roast date',
        'grind size',
        'per 250g',
        'SKU',
        'net weight',
        'product code',
        'size guide',
        'care instructions',
        'tasting notes',
        'batch number',
        'model number',
      ],
      provenance: [
        'direct trade',
        'micro-lot',
        'cooperatives',
        'small farms',
        'Q Grader',
        'wholesale accounts',
        'our workshop',
        'authorised stockist',
        'authorised dealer',
      ],
      logistics: [
        'Royal Mail',
        'Tracked 24',
        'Tracked 48',
        'Parcelforce',
        'DPD',
        'Evri',
        'DHL',
        'USPS',
        'FedEx',
        'order cutoff',
        'dispatched within',
        'click & collect',
        'UK mainland',
        'Highlands & Islands',
        'next working day',
      ],
    },
    es: {
      productTerms: [
        'referencias en stock',
        'referencias en catálogo',
        'uds',
        'ficha técnica',
        'peso neto',
        'código de producto',
        'guía de tallas',
        'fecha de tueste',
        'grano entero',
        'garantía legal',
        'número de lote',
        'instrucciones de lavado',
      ],
      provenance: [
        'tienda física',
        'nuestro almacén',
        'servicio técnico oficial',
        'distribuidor oficial',
        'Denominación de Origen',
        'cooperativas',
        'taller propio',
        'comercio directo',
        'tostamos',
        'venta al por mayor',
      ],
      logistics: [
        'GLS',
        'SEUR',
        'MRW',
        'Nacex',
        'Correos Express',
        'contrareembolso',
        'contra reembolso',
        'Península',
        'Baleares',
        'Canarias',
        'Ceuta y Melilla',
        'bultos',
        'recogida en tienda',
        'gastos de devolución',
      ],
    },
  },
};
