export const education = {
  id: 'education',
  aliases: [
    'education',
    'tutoring',
    'tuition',
    'tutors',
    'educacion',
    'academia',
    'academias',
    'clases particulares',
  ],
  terms: {
    en: {
      qualifications: [
        'GCSE',
        'GCSEs',
        'IGCSE',
        'A-Level',
        'A-Levels',
        '11+',
        'Common Entrance',
        'KS2 SATs',
        'KS3',
        'Key Stage 3',
        'BTEC',
        'IB Diploma',
        'Scottish Highers',
        'UCAS',
      ],
      credentials: [
        'AQA',
        'Edexcel',
        'OCR',
        'Eduqas',
        'WJEC',
        'PGCE',
        'QTS',
        'CELTA',
        'enhanced DBS',
        'DBS-checked',
        'safeguarding',
        'Ofsted',
        'examiner',
      ],
      formats: [
        'small-group tuition',
        'one-to-one tuition',
        'trial session',
        'past paper',
        'past papers',
        'mock exams',
        'exam technique',
        'revision course',
        'Easter revision',
        'half-term',
        'Year 11',
        'Year 13',
        'intake',
      ],
    },
    es: {
      qualifications: [
        '3.º ESO',
        '4.º ESO',
        'ESO y Bachillerato',
        'Educación Secundaria Obligatoria',
        'EvAU',
        'EBAU',
        'PEvAU',
        'selectividad',
        '2.º Bachillerato',
        'FP',
        'Grado Medio',
        'KET',
        'PET',
        'FCE',
        'B2 First',
        'C1 Advanced',
        'CPE',
        'DELE',
        'Escuela Oficial de Idiomas',
      ],
      credentials: [
        'Formación del Profesorado',
        'Máster del Profesorado',
        'CAP',
        'CELTA',
        'Filología',
        'examinadora',
        'examinador',
        'Cambridge Examiner',
        'centro preparador',
        'método ABN',
        'Consejería de Educación',
      ],
      formats: [
        'refuerzo escolar',
        'clases de apoyo',
        'grupos reducidos',
        'clase de prueba',
        'intensivo',
        'matrícula',
        'convocatoria extraordinaria',
        'primer trimestre',
        'técnicas de estudio',
        'recuperar asignaturas',
        'curso escolar',
      ],
    },
  },
};
