export const fitnessGym = {
  id: 'fitness-gym',
  aliases: ['fitness-gym', 'fitness', 'gym', 'gyms', 'gimnasio', 'gimnasios'],
  terms: {
    en: {
      disciplines: [
        'strength and conditioning',
        'Olympic lifting',
        'powerlifting',
        'weightlifting',
        'deadlift',
        'Romanian deadlifts',
        'bench press',
        'back squat',
        'hip hinge',
        'CrossFit',
        'Hyrox',
        'reformer pilates',
        'movement screen',
      ],
      credentials: [
        'UKSCA',
        'NSCA',
        'CSCS',
        'Level 3 PT',
        'Level 3 Personal Training',
        'CIMSPA',
        'Register of Exercise Professionals',
        'RYT-200',
        'CFSC',
        'British Weightlifting',
        'CrossFit Level 1',
        'Sport Science',
        'Active IQ',
      ],
      equipment: [
        'squat racks',
        'Eleiko',
        'bumper plates',
        'barbells',
        'Concept2',
        'rowing machines',
        'sprint track',
        'prowler',
        'kettlebells',
        'assault bike',
        'lifting platforms',
        'Rogue',
      ],
    },
    es: {
      disciplines: [
        'Pilates Reformer',
        'Pilates Mat',
        'entrenamiento funcional',
        'fuerza funcional',
        'Indoor Cycling',
        'yoga terapéutico',
        'evaluación postural',
        'halterofilia',
        'CrossFit',
        'hipopresivos',
        'calistenia',
      ],
      credentials: [
        'INEFC',
        'CAFyD',
        'Licenciado en CAFE',
        'Licenciada en CAFE',
        'Ciencias de la Actividad Física y del Deporte',
        'COLEF',
        'TSEAS',
        'TAFAD',
        'Yoga Alliance',
        'Body Control Pilates',
        'Schwinn',
        'STOTT Pilates',
        'Les Mills',
      ],
      equipment: [
        'cajones pliométricos',
        'barras olímpicas',
        'pared de escalada',
        'discos bumper',
        'kettlebells',
        'rack de sentadillas',
        'jaula de potencia',
        'Concept2',
        'Eleiko',
        'trineo',
        'plataformas de halterofilia',
      ],
    },
  },
};
