export const localRetail = {
  id: 'local-retail',
  aliases: [
    'local-retail',
    'retail',
    'local shop',
    'high street',
    'comercio local',
    'comercio',
    'tienda de barrio',
    'pequeño comercio',
  ],
  terms: {
    en: {
      stock: [
        'second-hand',
        'secondhand',
        'first edition',
        'first-edition',
        'hardback',
        'hardbacks',
        'paperback',
        'paperbacks',
        'out of print',
        'antiquarian',
        'facsimile',
        'OS Maps',
        'sketchbooks',
        'watercolour paper',
        'fountain pens',
      ],
      services: [
        'valuations',
        'house-clearance',
        'house clearance',
        'postal orders',
        'special orders',
        'bookseller',
        'cataloguer',
        'key cutting',
        'engraving',
        'photocopying',
        'laminating',
        'picture framing',
        'rubber stamps',
      ],
      brands: [
        'stockist',
        'authorised dealer',
        'Penguin',
        'Pelican',
        'Pelicans',
        'Collins',
        'Ordnance Survey',
        'Folio Society',
        'Moleskine',
        'Leuchtturm1917',
        'Staedtler',
        'Winsor & Newton',
        'Lamy',
      ],
    },
    es: {
      stock: [
        'cuadernos',
        'punteado',
        'pliego',
        'papel acuarela',
        'bellas artes',
        'material de dibujo',
        'rotuladores',
        'bolígrafos',
        'agendas',
        'recambio',
        'segunda mano',
        'primera edición',
        'tapa dura',
      ],
      services: [
        'encuadernación',
        'fotocopias',
        'plastificados',
        'por encargo',
        'TFG',
        'TFM',
        'sello personalizado',
        'copia de llaves',
        'reprografía',
        'enmarcación',
        'tasación',
      ],
      brands: [
        'distribuidor oficial',
        'distribuidora oficial',
        'Fabriano',
        'Staedtler',
        'Moleskine',
        'Leuchtturm1917',
        'Finocam',
        'Trodat',
        'APLI',
        'Faber-Castell',
        'Canson',
        'Stabilo',
        'Pilot',
      ],
    },
  },
};
