export const restaurants = {
  id: 'restaurants',
  aliases: [
    'restaurant',
    'restaurants',
    'bistro',
    'eatery',
    'restaurante',
    'restaurantes',
    'bar de tapas',
    'taberna',
  ],
  terms: {
    en: {
      dishes: [
        'small plates',
        'sourdough',
        'focaccia',
        'salt cod',
        'custard tart',
        'slow-braised',
        'salsa verde',
        'devilled eggs',
        'rice pudding',
        'lamb chops',
        'pork belly',
        'puddings',
        'charcuterie',
      ],
      service: [
        'set lunch',
        'sharing menu',
        'walk-ins',
        'last orders',
        'wine pairing',
        'by the glass',
        'private hire',
        'sous chef',
        'chef-owner',
        'corkage',
        'service charge',
        'pre-theatre',
        'Sunday roast',
      ],
      provenance: [
        'traceability',
        'West Country',
        'Cornish',
        'line-caught',
        'free-range',
        'dry-aged',
        'rare breed',
        'day-boat',
        'foraged',
        'natural wine',
        'low-intervention',
        'grass-fed',
      ],
    },
    es: {
      dishes: [
        'croquetas',
        'patatas bravas',
        'ensaladilla rusa',
        'rabas',
        'boquerones',
        'lentejas',
        'pil-pil',
        'torrija',
        'arroz con leche',
        'tortilla de patatas',
        'callos',
        'salmorejo',
        'pinchos',
        'raciones',
      ],
      service: [
        'menú del día',
        'primer plato',
        'segundo plato',
        'postre o café',
        'vino de la casa',
        'media ración',
        'barra',
        'caña',
        'vermut',
        'cortado',
        'sobremesa',
        'fuera de carta',
      ],
      provenance: [
        'denominación de origen',
        'almadraba',
        'Mercamadrid',
        'Mercabarna',
        'lonja',
        'cooperativa',
        'embutidos',
        'ternera gallega',
        'ibérico de bellota',
        'proveedor',
        'bodega',
      ],
    },
  },
};
