export const saasStartup = {
  id: 'saas-startup',
  aliases: [
    'saas',
    'saas-startup',
    'startup',
    'software',
    'b2b software',
    'software de gestion',
    'empresa de software',
  ],
  terms: {
    en: {
      capabilities: [
        'deposit collection',
        'double-booking',
        'touch-up queue',
        'flash sheet',
        'per-artist',
        'bookable slot',
        'enquiry inbox',
        'walk-in queue',
        'stock alerts',
        'cash-up',
        'job sheets',
        'staff rota',
        'timesheets',
      ],
      integrations: [
        'Stripe',
        'Google Calendar',
        'Mailchimp',
        'WhatsApp Business',
        'Xero',
        'QuickBooks',
        'Sage Accounting',
        'GoCardless',
        'SumUp',
        'Zettle',
        'FreeAgent',
        'Dext',
      ],
      pricingTerms: [
        'per chair',
        'per location',
        'per vehicle',
        'per technician',
        'per practitioner',
        'per room',
        'per till',
        'appointments/month',
        'multi-location',
      ],
    },
    es: {
      capabilities: [
        'cola sin cita',
        'historial de cortes',
        'agenda por silla',
        'control de stock',
        'resumen de caja',
        'cierre de caja',
        'terminal virtual',
        'tarjetas de fidelización',
        'ficha de cliente',
        'cobro de señal',
        'fichaje',
        'partes de trabajo',
        'cuadrante de turnos',
      ],
      integrations: [
        'Stripe',
        'Google Calendar',
        'Holded',
        'Factorial',
        'Contasimple',
        'Quipu',
        'Redsys',
        'Verifactu',
        'TicketBAI',
        'WhatsApp Business',
      ],
      pricingTerms: [
        'por silla',
        'por sillón',
        'por local',
        'por profesional',
        'por centro',
        'por vehículo',
        'por técnico',
        'techo plano',
      ],
    },
  },
};
